"""Live realtime application helpers."""

from nola.application.live.realtime.audio import (
    LiveRealtimeAudioFrameMetadata,
    LiveRealtimePcm16Frame,
    build_pcm16le_frame,
    ensure_pcm16le_contract,
    expected_pcm16le_byte_length,
    pcm16le_to_float32_waveform,
    validate_pcm16le_frame_metadata,
)
from nola.application.live.realtime.connection_registry import (
    LiveStreamConnectionRegistry,
)
from nola.application.live.realtime.diagnostics import (
    LiveRealtimeDiagnosticsWavFile,
    LiveRealtimeDiagnosticsWavStart,
    LiveRealtimeDiagnosticsWavStarted,
    LiveRealtimeDiagnosticsWavStopped,
    LiveRealtimeDiagnosticsWavStopReason,
    LiveRealtimeWavDiagnosticsSession,
    Pcm16WavWriter,
    default_diagnostics_output_dir,
    ensure_diagnostics_output_dir,
)
from nola.application.live.realtime.errors import (
    LiveRealtimeSessionError,
    LiveRealtimeTranscriberError,
)
from nola.application.live.realtime.mock_transcriber import (
    LIVE_REALTIME_MOCK_FINAL_SEGMENT_MS,
    LIVE_REALTIME_MOCK_PARTIAL_INTERVAL_MS,
    MockLiveRealtimeTranscriber,
)
from nola.application.live.realtime.protocol import (
    LIVE_REALTIME_AUDIO_BYTE_ORDER,
    LIVE_REALTIME_AUDIO_BYTES_PER_SAMPLE,
    LIVE_REALTIME_AUDIO_CHANNEL_COUNT,
    LIVE_REALTIME_AUDIO_ENCODING,
    LIVE_REALTIME_AUDIO_FRAME_MAX_BYTES,
    LIVE_REALTIME_AUDIO_FRAME_MAX_MS,
    LIVE_REALTIME_AUDIO_FRAME_MIN_MS,
    LIVE_REALTIME_AUDIO_SAMPLE_RATE,
    LIVE_REALTIME_DIAGNOSTICS_WAV_DEFAULT_MAX_BYTES,
    LIVE_REALTIME_DIAGNOSTICS_WAV_DEFAULT_MAX_DURATION_MS,
    LIVE_REALTIME_DIAGNOSTICS_WAV_MAX_BYTES,
    LIVE_REALTIME_DIAGNOSTICS_WAV_MAX_DURATION_MS,
    LIVE_REALTIME_ERROR_CODES,
    LIVE_REALTIME_PROTOCOL_VERSION,
    LIVE_REALTIME_SUPPORTED_PROTOCOL_VERSIONS,
    LiveRealtimeErrorCode,
)
from nola.application.live.realtime.session import (
    LiveRealtimeAudioFrameResult,
    LiveRealtimeSessionRuntime,
    LiveRealtimeTrackStart,
    LiveRealtimeTrackStop,
)
from nola.application.live.realtime.transcriber import (
    LiveRealtimeTranscriber,
    LiveRealtimeTranscriberFrame,
    LiveRealtimeTranscriberResult,
    LiveRealtimeTranscriptCommittedPartial,
    LiveRealtimeTranscriptEvent,
    LiveRealtimeTranscriptFinal,
    LiveRealtimeTranscriptFinalCandidate,
    LiveRealtimeTranscriptPreview,
)

__all__ = [
    "LIVE_REALTIME_AUDIO_BYTE_ORDER",
    "LIVE_REALTIME_AUDIO_BYTES_PER_SAMPLE",
    "LIVE_REALTIME_AUDIO_CHANNEL_COUNT",
    "LIVE_REALTIME_AUDIO_ENCODING",
    "LIVE_REALTIME_AUDIO_FRAME_MAX_BYTES",
    "LIVE_REALTIME_AUDIO_FRAME_MAX_MS",
    "LIVE_REALTIME_AUDIO_FRAME_MIN_MS",
    "LIVE_REALTIME_AUDIO_SAMPLE_RATE",
    "LIVE_REALTIME_DIAGNOSTICS_WAV_DEFAULT_MAX_BYTES",
    "LIVE_REALTIME_DIAGNOSTICS_WAV_DEFAULT_MAX_DURATION_MS",
    "LIVE_REALTIME_DIAGNOSTICS_WAV_MAX_BYTES",
    "LIVE_REALTIME_DIAGNOSTICS_WAV_MAX_DURATION_MS",
    "LIVE_REALTIME_ERROR_CODES",
    "LIVE_REALTIME_MOCK_FINAL_SEGMENT_MS",
    "LIVE_REALTIME_MOCK_PARTIAL_INTERVAL_MS",
    "LIVE_REALTIME_PROTOCOL_VERSION",
    "LIVE_REALTIME_SUPPORTED_PROTOCOL_VERSIONS",
    "LiveRealtimeDiagnosticsWavFile",
    "LiveRealtimeDiagnosticsWavStart",
    "LiveRealtimeDiagnosticsWavStarted",
    "LiveRealtimeDiagnosticsWavStopped",
    "LiveRealtimeDiagnosticsWavStopReason",
    "LiveRealtimeAudioFrameMetadata",
    "LiveRealtimeAudioFrameResult",
    "LiveRealtimeErrorCode",
    "LiveRealtimePcm16Frame",
    "LiveRealtimeSessionError",
    "LiveRealtimeTranscriberError",
    "LiveRealtimeSessionRuntime",
    "LiveStreamConnectionRegistry",
    "LiveRealtimeTranscriptEvent",
    "LiveRealtimeTranscriptCommittedPartial",
    "LiveRealtimeTranscriptFinal",
    "LiveRealtimeTranscriptFinalCandidate",
    "LiveRealtimeTranscriptPreview",
    "LiveRealtimeTranscriber",
    "LiveRealtimeTranscriberFrame",
    "LiveRealtimeTranscriberResult",
    "LiveRealtimeTrackStart",
    "LiveRealtimeTrackStop",
    "LiveRealtimeWavDiagnosticsSession",
    "MockLiveRealtimeTranscriber",
    "Pcm16WavWriter",
    "build_pcm16le_frame",
    "default_diagnostics_output_dir",
    "ensure_diagnostics_output_dir",
    "ensure_pcm16le_contract",
    "expected_pcm16le_byte_length",
    "pcm16le_to_float32_waveform",
    "validate_pcm16le_frame_metadata",
]
