/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get aggregated application configuration
     * @description Return the frontend-facing configuration view, including engine info, effective transcription defaults, transcription field metadata, upload constraints, and model-compatible language options.
     */
    get: operations['get_config_api_config_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config/transcription/engine-defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get raw transcription engine defaults
     * @description Return the non-batched WhisperModel defaults expanded with the full VadOptions default set, without any persisted application overrides.
     */
    get: operations['get_transcription_engine_defaults_api_config_transcription_engine_defaults_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config/transcription/defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Reset persisted transcription defaults
     * @description Delete the application-level transcription-defaults override layer and fall back to the raw engine defaults.
     */
    delete: operations['delete_transcription_defaults_api_config_transcription_defaults_delete']
    options?: never
    head?: never
    /**
     * Update persisted transcription defaults
     * @description Apply a partial update to the persisted application-level transcription defaults. Explicit null removes an override key, and nested objects are merged without replacing untouched subkeys.
     */
    patch: operations['patch_transcription_defaults_api_config_transcription_defaults_patch']
    trace?: never
  }
  '/api/config/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get effective export defaults
     * @description Return export defaults after applying persisted overrides on top of the built-in server defaults.
     */
    get: operations['get_export_config_api_config_export_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config/export/defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Reset persisted export defaults
     * @description Delete persisted export-default overrides and fall back to built-in server defaults.
     */
    delete: operations['delete_export_defaults_api_config_export_defaults_delete']
    options?: never
    head?: never
    /**
     * Update persisted export defaults
     * @description Apply a partial update to application-level export defaults. Explicit null removes an override key.
     */
    patch: operations['patch_export_defaults_api_config_export_defaults_patch']
    trace?: never
  }
  '/api/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all models
     * @description Return all registered models with local state and download progress.
     */
    get: operations['list_all_models_api_models_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/downloads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List active model downloads
     * @description Return active model downloads with real current speed snapshots.
     */
    get: operations['list_active_downloads_api_models_downloads_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get model settings
     * @description Return model directory configuration and override state.
     */
    get: operations['get_model_settings_api_models_settings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update model settings
     * @description Persist model directory configuration.
     */
    patch: operations['patch_model_settings_api_models_settings_patch']
    trace?: never
  }
  '/api/models/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Model download SSE stream
     * @description Stream model download progress events via SSE.
     */
    get: operations['model_events_api_models_events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{model_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get model detail
     * @description Return one model with full detail.
     */
    get: operations['get_model_detail_api_models__model_id__get']
    put?: never
    post?: never
    /**
     * Delete model cache
     * @description Delete local model cache (full or partial).
     */
    delete: operations['delete_model_api_models__model_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{model_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start model download
     * @description Accept a download request and start background download.
     */
    post: operations['start_download_api_models__model_id__download_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{model_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel model download
     * @description Cancel one active download.
     */
    post: operations['cancel_download_api_models__model_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{model_id}/select': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Select configured model
     * @description Set the configured model for next Worker startup.
     */
    post: operations['select_model_api_models__model_id__select_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Transcriptions
     * @description List all transcription tasks.
     *
     *     Args:
     *         status: Optional status filter
     *             (pending, processing, completed, failed, cancelled)
     *         limit: Maximum number of results
     *         offset: Pagination offset
     *         q: Optional filename search keyword
     *         sort_by: Sort field
     *         order: Sort order (asc or desc)
     *
     *     Returns:
     *         List of tasks with pagination info.
     */
    get: operations['list_transcriptions_api_transcription_tasks__get']
    put?: never
    /**
     * Create transcription task
     * @description Create a transcription task for an uploaded file.
     *
     *     Steps:
     *     1. Upload file via POST /api/files to get file_id.
     *     2. Create task via this endpoint with file_id and optional parameters.
     *     3. Worker processes the task asynchronously.
     *     4. Query status via GET /api/transcription-tasks/{task_id}.
     *
     *     All transcription parameters are optional. If omitted, the effective defaults
     *     (engine defaults plus persisted application overrides) are used.
     */
    post: operations['create_transcription_api_transcription_tasks__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Transcription
     * @description Get transcription task status and result.
     *
     *     Args:
     *         task_id: Task identifier
     *
     *     Returns:
     *         Task status and result.
     */
    get: operations['get_transcription_api_transcription_tasks__task_id__get']
    put?: never
    post?: never
    /**
     * Cancel Transcription
     * @description Cancel a transcription task.
     *
     *     Args:
     *         task_id: Task identifier
     *
     *     Returns:
     *         Cancellation result.
     */
    delete: operations['cancel_transcription_api_transcription_tasks__task_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/batch/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Batch cancel transcription tasks
     * @description Cancel multiple tasks and return per-task outcomes.
     */
    post: operations['batch_cancel_transcriptions_api_transcription_tasks_batch_cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/batch/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Batch retry transcription tasks
     * @description Retry failed or cancelled tasks by creating new pending tasks.
     */
    post: operations['batch_retry_transcriptions_api_transcription_tasks_batch_retry_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/{task_id}/record': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete task record
     * @description Delete a terminal task record without deleting its file.
     */
    delete: operations['delete_task_api_transcription_tasks__task_id__record_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/{task_id}/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export transcription result
     * @description Export completed transcription as subtitle file.
     *
     *     Supports SRT, VTT, TXT, and ASS formats.
     *     Use save=true to store file on server, save=false to download directly.
     */
    get: operations['export_transcription_api_transcription_tasks__task_id__export_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transcription-tasks/export/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Batch export transcriptions
     * @description Export multiple transcriptions as a ZIP archive.
     *
     *     Failed tasks are skipped and logged in _errors.txt within the archive.
     */
    post: operations['batch_export_api_transcription_tasks_export_batch_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all uploaded files
     * @description List all uploaded files with pagination.
     */
    get: operations['list_files_api_files__get']
    put?: never
    /**
     * Upload an audio file
     * @description Upload an audio file for later transcription.
     *
     *     The file is saved to the server and a file_id is returned.
     *     Use this file_id to create transcription tasks.
     *
     *     Supported formats: mp3, wav, flac, m4a, ogg, webm, aac
     *     Max file size: 500 MB
     */
    post: operations['upload_file_api_files__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/check-integrity': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check database-file consistency
     * @description Check consistency between database records and files on disk.
     *
     *     Returns a list of 'missing_files' - database records that reference
     *     files which no longer exist on disk. This can happen if files are
     *     manually deleted from the uploads directory.
     */
    get: operations['check_integrity_api_files_check_integrity_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/cleanup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Remove orphan database records
     * @description Remove database records for files that no longer exist on disk.
     *
     *     This is useful after manually deleting files from the uploads directory.
     *     Use GET /check-integrity first to see what will be cleaned up.
     */
    post: operations['cleanup_orphans_api_files_cleanup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{file_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get file metadata
     * @description Get file metadata.
     *
     *     Args:
     *         file_id: File identifier
     *
     *     Returns:
     *         File metadata
     */
    get: operations['get_file_api_files__file_id__get']
    put?: never
    post?: never
    /**
     * Delete a file
     * @description Delete file metadata when no task records still reference it.
     *
     *     Args:
     *         file_id: File identifier
     *
     *     Returns:
     *         Deletion confirmation
     */
    delete: operations['delete_file_api_files__file_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Return health status.
     */
    get: operations['health_check_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Root
     * @description Return API information.
     */
    get: operations['root__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ActiveModelDownloadResponse
     * @description Expose one active model download with registry identity.
     */
    ActiveModelDownloadResponse: {
      /** Model Id */
      model_id: string
      /** Name */
      name: string
      /**
       * Status
       * @enum {string}
       */
      status: 'downloading' | 'completed' | 'failed' | 'cancelled'
      /** Percent */
      percent: number
      /** Downloaded Bytes */
      downloaded_bytes: number
      /** Total Bytes */
      total_bytes: number
      /** Speed Bps */
      speed_bps: number
      /** Error */
      error?: string | null
    }
    /**
     * ActiveModelDownloadsResponse
     * @description Expose the current active-download runtime summary.
     */
    ActiveModelDownloadsResponse: {
      /** Downloads */
      downloads: components['schemas']['ActiveModelDownloadResponse'][]
      /** Active Count */
      active_count: number
      /** Total Speed Bps */
      total_speed_bps: number
    }
    /**
     * AppConfigResponse
     * @description Aggregate application configuration required by the frontend.
     */
    AppConfigResponse: {
      engine: components['schemas']['EngineConfigResponse']
      transcription: components['schemas']['TranscriptionConfigResponse']
      file: components['schemas']['FileConfigResponse']
      /** Effective Languages */
      effective_languages: components['schemas']['LanguageOptionSchema'][]
      model?: components['schemas']['ModelConfigResponse'] | null
    }
    /**
     * BatchExportRequest
     * @description Batch export request for multiple transcriptions.
     */
    BatchExportRequest: {
      /**
       * Task Ids
       * @description List of task IDs to export
       */
      task_ids: string[]
      /** @description Output format for all files. If omitted, resolve from persisted export defaults. */
      format?: components['schemas']['ExportFormat'] | null
      /**
       * Include Timestamps
       * @description Include timestamps in TXT format. If omitted, resolve from persisted export defaults.
       */
      include_timestamps?: boolean | null
      /**
       * Zip Name
       * @description Custom ZIP filename (without extension)
       */
      zip_name?: string | null
    }
    /**
     * BatchTaskActionRequest
     * @description Batch action request for task-level operations.
     */
    BatchTaskActionRequest: {
      /**
       * Task Ids
       * @description List of task IDs to process
       */
      task_ids: string[]
    }
    /**
     * BatchTaskActionResponse
     * @description Response for batch cancel/retry actions.
     */
    BatchTaskActionResponse: {
      /**
       * Action
       * @enum {string}
       */
      action: 'cancel' | 'retry'
      summary: components['schemas']['BatchTaskActionSummaryResponse']
      /** Results */
      results: components['schemas']['BatchTaskActionResultResponse'][]
    }
    /**
     * BatchTaskActionResultResponse
     * @description Per-task result for batch task actions.
     */
    BatchTaskActionResultResponse: {
      /** Task Id */
      task_id: string
      /** Ok */
      ok: boolean
      /** Message */
      message: string
      /** Error Code */
      error_code?: ('not_found' | 'invalid_status' | 'duplicate_task_id' | 'file_missing') | null
      /** Status */
      status?: ('pending' | 'processing' | 'completed' | 'failed' | 'cancelled') | null
      /** New Task Id */
      new_task_id?: string | null
      /** File Id */
      file_id?: string | null
      /** Filename */
      filename?: string | null
    }
    /**
     * BatchTaskActionSummaryResponse
     * @description Batch task action summary counts.
     */
    BatchTaskActionSummaryResponse: {
      /** Requested */
      requested: number
      /** Succeeded */
      succeeded: number
      /** Failed */
      failed: number
    }
    /** Body_upload_file_api_files__post */
    Body_upload_file_api_files__post: {
      /**
       * File
       * Format: binary
       * @description Audio file to upload
       */
      file: string
    }
    /**
     * CancelTaskResponse
     * @description Task cancellation response.
     */
    CancelTaskResponse: {
      /** Task Id */
      task_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
      /** Message */
      message: string
      task: components['schemas']['TaskSummaryResponse']
    }
    /**
     * CleanupResponse
     * @description Orphan cleanup result.
     */
    CleanupResponse: {
      /** Message */
      message: string
      /** Deleted Count */
      deleted_count: number
      /** Deleted Files */
      deleted_files: components['schemas']['MissingFileInfo'][]
    }
    /**
     * CreateTaskResponse
     * @description Task creation response.
     */
    CreateTaskResponse: {
      /** Task Id */
      task_id: string
      /** File Id */
      file_id: string
      /** Filename */
      filename: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
      /** Options */
      options: {
        [key: string]: unknown
      } | null
      /** Model Id */
      model_id?: string | null
    }
    /**
     * DeleteResponse
     * @description Generic deletion confirmation.
     */
    DeleteResponse: {
      /** Message */
      message: string
    }
    /**
     * DeleteTaskRecordResponse
     * @description Task record deletion response.
     */
    DeleteTaskRecordResponse: {
      /** Task Id */
      task_id: string
      /** Message */
      message: string
    }
    /**
     * DetailResponse
     * @description Expose one JSON error detail message.
     */
    DetailResponse: {
      /** Detail */
      detail: string
    }
    /**
     * DownloadProgressResponse
     * @description Expose one active download snapshot.
     */
    DownloadProgressResponse: {
      /** Percent */
      percent: number
      /** Downloaded Bytes */
      downloaded_bytes: number
      /** Total Bytes */
      total_bytes: number
      /** Speed Bps */
      speed_bps: number
      /** Error */
      error?: string | null
    }
    /**
     * EngineConfigResponse
     * @description Expose the active engine configuration.
     */
    EngineConfigResponse: {
      /** Model Size */
      model_size: string
      /** Device */
      device: string
      /** Compute Type */
      compute_type: string
      /** Is Multilingual */
      is_multilingual: boolean
    }
    /**
     * EngineDefaultsResponse
     * @description Return the raw engine defaults without application overrides.
     */
    EngineDefaultsResponse: {
      defaults: components['schemas']['TranscriptionResolvedDefaultsResponse']
    }
    /**
     * ExportConfigResponse
     * @description Expose effective export defaults required by frontend clients.
     */
    ExportConfigResponse: {
      defaults: components['schemas']['ExportResolvedDefaultsResponse']
    }
    /**
     * ExportDefaultsPatchResponse
     * @description Return effective export defaults after a PATCH update.
     */
    ExportDefaultsPatchResponse: {
      defaults: components['schemas']['ExportResolvedDefaultsResponse']
    }
    /**
     * ExportDefaultsUpdateRequest
     * @description Partial update payload for application-level export defaults.
     * @example {
     *       "format": "vtt",
     *       "include_timestamps": false
     *     }
     */
    ExportDefaultsUpdateRequest: {
      /** @description Default export format */
      format?: components['schemas']['ExportFormat'] | null
      /**
       * Include Timestamps
       * @description Whether TXT export includes timestamp prefixes by default
       */
      include_timestamps?: boolean | null
    }
    /**
     * ExportFormat
     * @description Supported export format identifiers.
     * @enum {string}
     */
    ExportFormat: 'srt' | 'vtt' | 'txt' | 'ass'
    /**
     * ExportResolvedDefaultsResponse
     * @description Expose fully resolved export defaults used at runtime.
     */
    ExportResolvedDefaultsResponse: {
      format: components['schemas']['ExportFormat']
      /** Include Timestamps */
      include_timestamps: boolean
    }
    /**
     * FileConfigResponse
     * @description Expose upload-related configuration needed by the frontend.
     */
    FileConfigResponse: {
      /** Allowed Extensions */
      allowed_extensions: string[]
      /** Allowed Mime Types */
      allowed_mime_types: string[]
      /** Max File Size */
      max_file_size: number
    }
    /**
     * FileListResponse
     * @description Paginated file list response.
     */
    FileListResponse: {
      /** Files */
      files: components['schemas']['FileResponse'][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /**
     * FileResponse
     * @description Single file metadata response.
     */
    FileResponse: {
      /** File Id */
      file_id: string
      /** Filename */
      filename: string
      /** Size */
      size: number
      /** Content Type */
      content_type: string | null
      /** Created At */
      created_at: string
    }
    /**
     * FileUploadResponse
     * @description File upload success response.
     */
    FileUploadResponse: {
      /** File Id */
      file_id: string
      /** Filename */
      filename: string
      /** Size */
      size: number
      /** Content Type */
      content_type: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * IntegrityCheckResponse
     * @description File integrity check result.
     */
    IntegrityCheckResponse: {
      /** Status */
      status: string
      /** Missing Files */
      missing_files: components['schemas']['MissingFileInfo'][]
      /** Missing Count */
      missing_count: number
    }
    /**
     * LanguageOptionSchema
     * @description Describe one selectable language option.
     */
    LanguageOptionSchema: {
      /** Code */
      code: string
      /** Label Key */
      label_key: string
    }
    /**
     * MissingFileInfo
     * @description Info about a file record missing from disk.
     */
    MissingFileInfo: {
      /** Id */
      id: string
      /** Filename */
      filename: string
      /** Path */
      path: string
    }
    /**
     * ModelCancelResponse
     * @description Confirm a download cancellation.
     */
    ModelCancelResponse: {
      /** Model Id */
      model_id: string
      /** Message */
      message: string
    }
    /**
     * ModelConfigResponse
     * @description Expose model state inside the aggregated /api/config response.
     */
    ModelConfigResponse: {
      /** Configured Model Id */
      configured_model_id?: string | null
      /** Last Loaded Model Id */
      last_loaded_model_id?: string | null
      /**
       * Restart Required
       * @default false
       */
      restart_required: boolean
    }
    /**
     * ModelDeleteResponse
     * @description Confirm a model cache deletion.
     */
    ModelDeleteResponse: {
      /** Model Id */
      model_id: string
      /** Message */
      message: string
    }
    /**
     * ModelDetailResponse
     * @description Return one model with full detail.
     */
    ModelDetailResponse: {
      /** Model Id */
      model_id: string
      /** Name */
      name: string
      /** Size Bytes */
      size_bytes: number
      /** Repo Id */
      repo_id: string
      /** Languages */
      languages: string
      /** Speed Rank */
      speed_rank: number
      /** Accuracy Rank */
      accuracy_rank: number
      /** Description */
      description: string
      /** Description Key */
      description_key: string
      /**
       * Status
       * @enum {string}
       */
      status: 'not_downloaded' | 'downloading' | 'partial_download' | 'downloaded'
      /** Disk Usage */
      disk_usage?: number | null
      /**
       * Is Configured
       * @default false
       */
      is_configured: boolean
      /**
       * Is Last Loaded
       * @default false
       */
      is_last_loaded: boolean
      download_progress?: components['schemas']['DownloadProgressResponse'] | null
    }
    /**
     * ModelDownloadStartedResponse
     * @description Confirm a download was accepted.
     */
    ModelDownloadStartedResponse: {
      /** Model Id */
      model_id: string
      /**
       * Status
       * @default downloading
       * @enum {string}
       */
      status: 'not_downloaded' | 'downloading' | 'partial_download' | 'downloaded'
      /** Message */
      message: string
    }
    /**
     * ModelListResponse
     * @description Return all models with global config state.
     */
    ModelListResponse: {
      /** Models */
      models: components['schemas']['ModelResponse'][]
      /** Configured Model Id */
      configured_model_id?: string | null
      /** Last Loaded Model Id */
      last_loaded_model_id?: string | null
      /** Effective Model Dir */
      effective_model_dir: string
    }
    /**
     * ModelResponse
     * @description Expose one model with registry info, local state, and config flags.
     */
    ModelResponse: {
      /** Model Id */
      model_id: string
      /** Name */
      name: string
      /** Size Bytes */
      size_bytes: number
      /** Repo Id */
      repo_id: string
      /** Languages */
      languages: string
      /** Speed Rank */
      speed_rank: number
      /** Accuracy Rank */
      accuracy_rank: number
      /** Description */
      description: string
      /** Description Key */
      description_key: string
      /**
       * Status
       * @enum {string}
       */
      status: 'not_downloaded' | 'downloading' | 'partial_download' | 'downloaded'
      /** Disk Usage */
      disk_usage?: number | null
      /**
       * Is Configured
       * @default false
       */
      is_configured: boolean
      /**
       * Is Last Loaded
       * @default false
       */
      is_last_loaded: boolean
      download_progress?: components['schemas']['DownloadProgressResponse'] | null
    }
    /**
     * ModelSelectResponse
     * @description Confirm a configured-model switch.
     */
    ModelSelectResponse: {
      /** Configured Model Id */
      configured_model_id: string
      /** Restart Required */
      restart_required: boolean
      /** Message */
      message: string
    }
    /**
     * ModelSettingsResponse
     * @description Expose model directory configuration and override state.
     */
    ModelSettingsResponse: {
      /** Configured Model Id */
      configured_model_id?: string | null
      /** Last Loaded Model Id */
      last_loaded_model_id?: string | null
      /** Configured Model Dir */
      configured_model_dir?: string | null
      /** Effective Model Dir */
      effective_model_dir: string
      /**
       * Override Source
       * @enum {string}
       */
      override_source: 'environment' | 'database' | 'default'
      /**
       * Restart Required
       * @default false
       */
      restart_required: boolean
    }
    /**
     * ModelSettingsUpdateRequest
     * @description Accept a partial model-settings update.
     */
    ModelSettingsUpdateRequest: {
      /**
       * Configured Model Dir
       * @description Absolute path for the model cache root directory.
       */
      configured_model_dir?: string | null
    }
    /**
     * NumberFieldSchema
     * @description Describe a numeric text input field.
     */
    NumberFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'number'
      /** Min */
      min?: number | null
      /** Max */
      max?: number | null
      /** Step */
      step?: number | null
      /** Depends On */
      depends_on?: string | null
      /** Special Values */
      special_values?: string[] | null
    }
    /**
     * NumberListFieldSchema
     * @description Describe a comma-separated numeric list field.
     */
    NumberListFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'number_list'
      /**
       * Allow Negative
       * @default false
       */
      allow_negative: boolean
      /**
       * Integer Only
       * @default false
       */
      integer_only: boolean
      /**
       * Collapse Single Value
       * @default false
       */
      collapse_single_value: boolean
      /** Depends On */
      depends_on?: string | null
    }
    /**
     * OptionGroupSchema
     * @description Group related option fields under one UI section.
     */
    OptionGroupSchema: {
      /** Group */
      group: string
      /** Group Label Key */
      group_label_key: string
      /** Fields */
      fields: (
        | components['schemas']['SliderFieldSchema']
        | components['schemas']['SwitchFieldSchema']
        | components['schemas']['NumberFieldSchema']
        | components['schemas']['NumberListFieldSchema']
        | components['schemas']['TextFieldSchema']
        | components['schemas']['SelectFieldSchema']
      )[]
    }
    /**
     * SavedExportResponse
     * @description Response when export is saved to server (save=true).
     */
    SavedExportResponse: {
      /** Saved Path */
      saved_path: string
    }
    /**
     * SegmentResponse
     * @description Single transcription segment.
     */
    SegmentResponse: {
      /** Start */
      start: number
      /** End */
      end: number
      /** Text */
      text: string
    }
    /**
     * SelectFieldSchema
     * @description Describe a single-select field.
     */
    SelectFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'select'
      /** Options */
      options?: components['schemas']['SelectOptionSchema'][] | null
      /** Options Source */
      options_source?: 'effective_languages' | null
      /** Depends On */
      depends_on?: string | null
    }
    /**
     * SelectOptionSchema
     * @description Describe one selectable option entry.
     */
    SelectOptionSchema: {
      /** Value */
      value: string
      /** Label Key */
      label_key: string
    }
    /**
     * SliderFieldSchema
     * @description Describe a slider-backed numeric field.
     */
    SliderFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'slider'
      /** Min */
      min: number
      /** Max */
      max: number
      /** Step */
      step: number
      /** Depends On */
      depends_on?: string | null
    }
    /**
     * SwitchFieldSchema
     * @description Describe a boolean toggle field.
     */
    SwitchFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'switch'
      /** Depends On */
      depends_on?: string | null
    }
    /**
     * TaskDetailResponse
     * @description Full task detail with transcription result.
     */
    TaskDetailResponse: {
      /** Task Id */
      task_id: string
      /** File Id */
      file_id: string
      /** Filename */
      filename?: string | null
      /** Model Id */
      model_id?: string | null
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
      /** Progress */
      progress: number
      /** Created At */
      created_at: string
      /** Completed At */
      completed_at: string | null
      /** Duration */
      duration: number | null
      /** Segments */
      segments: components['schemas']['SegmentResponse'][] | null
      /** Error */
      error: string | null
    }
    /**
     * TaskListResponse
     * @description Paginated task list response.
     */
    TaskListResponse: {
      /** Tasks */
      tasks: components['schemas']['TaskSummaryResponse'][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /**
     * TaskSummaryResponse
     * @description Task in list view (no segments).
     */
    TaskSummaryResponse: {
      /** Task Id */
      task_id: string
      /** File Id */
      file_id: string
      /** Filename */
      filename?: string | null
      /** Model Id */
      model_id?: string | null
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
      /** Progress */
      progress: number
      /** Created At */
      created_at: string
      /** Completed At */
      completed_at: string | null
    }
    /**
     * TextFieldSchema
     * @description Describe a free-form text field.
     */
    TextFieldSchema: {
      /** Key */
      key: string
      /** Label Key */
      label_key: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'text'
      /** Depends On */
      depends_on?: string | null
    }
    /**
     * TranscriptionConfigResponse
     * @description Expose effective transcription defaults and field metadata.
     */
    TranscriptionConfigResponse: {
      defaults: components['schemas']['TranscriptionResolvedDefaultsResponse']
      /** Schema */
      schema: components['schemas']['OptionGroupSchema'][]
    }
    /**
     * TranscriptionDefaultsPatchResponse
     * @description Return the effective defaults after a PATCH update.
     */
    TranscriptionDefaultsPatchResponse: {
      defaults: components['schemas']['TranscriptionResolvedDefaultsResponse']
    }
    /**
     * TranscriptionDefaultsUpdateRequest
     * @description Partial update payload for application-level transcription defaults.
     * @example {
     *       "beam_size": 3,
     *       "language": "zh",
     *       "vad_parameters": {
     *         "threshold": 0.6
     *       }
     *     }
     */
    TranscriptionDefaultsUpdateRequest: {
      /**
       * Language
       * @description Language code. Auto-detect if omitted.
       * @example en
       * @example zh
       * @example ja
       */
      language?: string | null
      /**
       * Task
       * @description Task value defined by backend transcription schema
       * @example transcribe
       */
      task?: string | null
      /**
       * Beam Size
       * @description Beam size for decoding
       * @example 5
       */
      beam_size?: number | null
      /**
       * Best Of
       * @description Number of candidates
       * @example 5
       */
      best_of?: number | null
      /**
       * Patience
       * @description Beam search patience
       * @example 1
       */
      patience?: number | null
      /**
       * Length Penalty
       * @description Length penalty
       * @example 1
       */
      length_penalty?: number | null
      /**
       * Repetition Penalty
       * @description Repetition penalty
       * @example 1
       */
      repetition_penalty?: number | null
      /**
       * No Repeat Ngram Size
       * @description No repeat n-gram size
       * @example 0
       */
      no_repeat_ngram_size?: number | null
      /**
       * Temperature
       * @description Sampling temperature(s)
       * @example [
       *       0,
       *       0.2,
       *       0.4,
       *       0.6,
       *       0.8,
       *       1
       *     ]
       */
      temperature?: number | number[] | null
      /**
       * Compression Ratio Threshold
       * @description Compression ratio threshold
       * @example 2.4
       */
      compression_ratio_threshold?: number | null
      /**
       * Log Prob Threshold
       * @description Log probability threshold
       * @example -1
       */
      log_prob_threshold?: number | null
      /**
       * No Speech Threshold
       * @description No speech threshold
       * @example 0.6
       */
      no_speech_threshold?: number | null
      /**
       * Condition On Previous Text
       * @description Condition on previous text
       * @example true
       */
      condition_on_previous_text?: boolean | null
      /**
       * Prompt Reset On Temperature
       * @description Reset prompt on temperature
       * @example 0.5
       */
      prompt_reset_on_temperature?: number | null
      /**
       * Initial Prompt
       * @description Initial prompt for context
       * @example
       */
      initial_prompt?: string | null
      /**
       * Prefix
       * @description Prefix for each segment
       * @example
       */
      prefix?: string | null
      /**
       * Hotwords
       * @description Hotwords to boost recognition
       * @example
       */
      hotwords?: string | null
      /**
       * Suppress Blank
       * @description Suppress blank outputs
       * @example true
       */
      suppress_blank?: boolean | null
      /**
       * Suppress Tokens
       * @description Token IDs to suppress
       * @example [
       *       -1
       *     ]
       */
      suppress_tokens?: number[] | null
      /**
       * Max New Tokens
       * @description Max new tokens per segment
       */
      max_new_tokens?: number | null
      /**
       * Without Timestamps
       * @description Disable timestamps
       * @example false
       */
      without_timestamps?: boolean | null
      /**
       * Max Initial Timestamp
       * @description Max initial timestamp
       * @example 1
       */
      max_initial_timestamp?: number | null
      /**
       * Word Timestamps
       * @description Enable word-level timestamps
       * @example false
       */
      word_timestamps?: boolean | null
      /**
       * Prepend Punctuations
       * @description Punctuations to prepend
       * @example "'“¿([{-
       */
      prepend_punctuations?: string | null
      /**
       * Append Punctuations
       * @description Punctuations to append
       * @example "'.。,，!！?？:：”)]}、
       */
      append_punctuations?: string | null
      /**
       * Vad Filter
       * @description Enable VAD filtering
       * @example false
       */
      vad_filter?: boolean | null
      /** @description VAD parameters */
      vad_parameters?: components['schemas']['VadParametersRequest'] | null
      /**
       * Multilingual
       * @description Enable multilingual mode
       * @example false
       */
      multilingual?: boolean | null
      /**
       * Chunk Length
       * @description Chunk length in seconds
       */
      chunk_length?: number | null
      /**
       * Clip Timestamps
       * @description Clip timestamps
       * @example 0
       */
      clip_timestamps?: string | number[] | null
      /**
       * Hallucination Silence Threshold
       * @description Hallucination silence threshold
       */
      hallucination_silence_threshold?: number | null
      /**
       * Language Detection Threshold
       * @description Language detection threshold
       * @example 0.5
       */
      language_detection_threshold?: number | null
      /**
       * Language Detection Segments
       * @description Segments for language detection
       * @example 1
       */
      language_detection_segments?: number | null
    }
    /**
     * TranscriptionRequest
     * @description Transcription request payload for creating a task.
     * @example {
     *       "append_punctuations": "\"'.。,，!！?？:：”)]}、",
     *       "beam_size": 5,
     *       "best_of": 5,
     *       "clip_timestamps": "0",
     *       "compression_ratio_threshold": 2.4,
     *       "condition_on_previous_text": true,
     *       "file_id": "uploaded-file-id",
     *       "language_detection_segments": 1,
     *       "language_detection_threshold": 0.5,
     *       "length_penalty": 1,
     *       "log_prob_threshold": -1,
     *       "max_initial_timestamp": 1,
     *       "multilingual": false,
     *       "no_repeat_ngram_size": 0,
     *       "no_speech_threshold": 0.6,
     *       "patience": 1,
     *       "prepend_punctuations": "\"'“¿([{-",
     *       "prompt_reset_on_temperature": 0.5,
     *       "repetition_penalty": 1,
     *       "suppress_blank": true,
     *       "suppress_tokens": [
     *         -1
     *       ],
     *       "task": "transcribe",
     *       "temperature": [
     *         0,
     *         0.2,
     *         0.4,
     *         0.6,
     *         0.8,
     *         1
     *       ],
     *       "vad_filter": false,
     *       "without_timestamps": false,
     *       "word_timestamps": false
     *     }
     */
    TranscriptionRequest: {
      /**
       * Language
       * @description Language code. Auto-detect if omitted.
       * @example en
       * @example zh
       * @example ja
       */
      language?: string | null
      /**
       * Task
       * @description Task value defined by backend transcription schema
       * @example transcribe
       */
      task?: string | null
      /**
       * Beam Size
       * @description Beam size for decoding
       * @example 5
       */
      beam_size?: number | null
      /**
       * Best Of
       * @description Number of candidates
       * @example 5
       */
      best_of?: number | null
      /**
       * Patience
       * @description Beam search patience
       * @example 1
       */
      patience?: number | null
      /**
       * Length Penalty
       * @description Length penalty
       * @example 1
       */
      length_penalty?: number | null
      /**
       * Repetition Penalty
       * @description Repetition penalty
       * @example 1
       */
      repetition_penalty?: number | null
      /**
       * No Repeat Ngram Size
       * @description No repeat n-gram size
       * @example 0
       */
      no_repeat_ngram_size?: number | null
      /**
       * Temperature
       * @description Sampling temperature(s)
       * @example [
       *       0,
       *       0.2,
       *       0.4,
       *       0.6,
       *       0.8,
       *       1
       *     ]
       */
      temperature?: number | number[] | null
      /**
       * Compression Ratio Threshold
       * @description Compression ratio threshold
       * @example 2.4
       */
      compression_ratio_threshold?: number | null
      /**
       * Log Prob Threshold
       * @description Log probability threshold
       * @example -1
       */
      log_prob_threshold?: number | null
      /**
       * No Speech Threshold
       * @description No speech threshold
       * @example 0.6
       */
      no_speech_threshold?: number | null
      /**
       * Condition On Previous Text
       * @description Condition on previous text
       * @example true
       */
      condition_on_previous_text?: boolean | null
      /**
       * Prompt Reset On Temperature
       * @description Reset prompt on temperature
       * @example 0.5
       */
      prompt_reset_on_temperature?: number | null
      /**
       * Initial Prompt
       * @description Initial prompt for context
       * @example
       */
      initial_prompt?: string | null
      /**
       * Prefix
       * @description Prefix for each segment
       * @example
       */
      prefix?: string | null
      /**
       * Hotwords
       * @description Hotwords to boost recognition
       * @example
       */
      hotwords?: string | null
      /**
       * Suppress Blank
       * @description Suppress blank outputs
       * @example true
       */
      suppress_blank?: boolean | null
      /**
       * Suppress Tokens
       * @description Token IDs to suppress
       * @example [
       *       -1
       *     ]
       */
      suppress_tokens?: number[] | null
      /**
       * Max New Tokens
       * @description Max new tokens per segment
       */
      max_new_tokens?: number | null
      /**
       * Without Timestamps
       * @description Disable timestamps
       * @example false
       */
      without_timestamps?: boolean | null
      /**
       * Max Initial Timestamp
       * @description Max initial timestamp
       * @example 1
       */
      max_initial_timestamp?: number | null
      /**
       * Word Timestamps
       * @description Enable word-level timestamps
       * @example false
       */
      word_timestamps?: boolean | null
      /**
       * Prepend Punctuations
       * @description Punctuations to prepend
       * @example "'“¿([{-
       */
      prepend_punctuations?: string | null
      /**
       * Append Punctuations
       * @description Punctuations to append
       * @example "'.。,，!！?？:：”)]}、
       */
      append_punctuations?: string | null
      /**
       * Vad Filter
       * @description Enable VAD filtering
       * @example false
       */
      vad_filter?: boolean | null
      /** @description VAD parameters */
      vad_parameters?: components['schemas']['VadParametersRequest'] | null
      /**
       * Multilingual
       * @description Enable multilingual mode
       * @example false
       */
      multilingual?: boolean | null
      /**
       * Chunk Length
       * @description Chunk length in seconds
       */
      chunk_length?: number | null
      /**
       * Clip Timestamps
       * @description Clip timestamps
       * @example 0
       */
      clip_timestamps?: string | number[] | null
      /**
       * Hallucination Silence Threshold
       * @description Hallucination silence threshold
       */
      hallucination_silence_threshold?: number | null
      /**
       * Language Detection Threshold
       * @description Language detection threshold
       * @example 0.5
       */
      language_detection_threshold?: number | null
      /**
       * Language Detection Segments
       * @description Segments for language detection
       * @example 1
       */
      language_detection_segments?: number | null
      /**
       * File Id
       * @description File ID from upload API
       */
      file_id: string
      /**
       * Model Id
       * @description Target model id (reserved, not used in execution yet).
       */
      model_id?: string | null
    }
    /**
     * TranscriptionResolvedDefaultsResponse
     * @description Expose fully resolved transcription defaults used at runtime.
     */
    TranscriptionResolvedDefaultsResponse: {
      /** Language */
      language: string | null
      /** Task */
      task: string
      /** Beam Size */
      beam_size: number
      /** Best Of */
      best_of: number
      /** Patience */
      patience: number
      /** Length Penalty */
      length_penalty: number
      /** Repetition Penalty */
      repetition_penalty: number
      /** No Repeat Ngram Size */
      no_repeat_ngram_size: number
      /** Temperature */
      temperature: number | number[]
      /** Compression Ratio Threshold */
      compression_ratio_threshold: number | null
      /** Log Prob Threshold */
      log_prob_threshold: number | null
      /** No Speech Threshold */
      no_speech_threshold: number | null
      /** Condition On Previous Text */
      condition_on_previous_text: boolean
      /** Prompt Reset On Temperature */
      prompt_reset_on_temperature: number
      /** Initial Prompt */
      initial_prompt: string | null
      /** Prefix */
      prefix: string | null
      /** Hotwords */
      hotwords: string | null
      /** Suppress Blank */
      suppress_blank: boolean
      /** Suppress Tokens */
      suppress_tokens: number[] | null
      /** Max New Tokens */
      max_new_tokens: number | null
      /** Without Timestamps */
      without_timestamps: boolean
      /** Max Initial Timestamp */
      max_initial_timestamp: number
      /** Word Timestamps */
      word_timestamps: boolean
      /** Prepend Punctuations */
      prepend_punctuations: string
      /** Append Punctuations */
      append_punctuations: string
      /** Vad Filter */
      vad_filter: boolean
      vad_parameters: components['schemas']['VadParametersDefaultsResponse']
      /** Multilingual */
      multilingual: boolean
      /** Chunk Length */
      chunk_length: number | null
      /** Clip Timestamps */
      clip_timestamps: string | number[]
      /** Hallucination Silence Threshold */
      hallucination_silence_threshold: number | null
      /** Language Detection Threshold */
      language_detection_threshold: number | null
      /** Language Detection Segments */
      language_detection_segments: number
    }
    /**
     * VadParametersDefaultsResponse
     * @description Expose expanded VAD defaults in API-safe form.
     */
    VadParametersDefaultsResponse: {
      /** Threshold */
      threshold: number
      /** Neg Threshold */
      neg_threshold: number | null
      /** Min Speech Duration Ms */
      min_speech_duration_ms: number
      /** Max Speech Duration S */
      max_speech_duration_s: number | 'inf'
      /** Min Silence Duration Ms */
      min_silence_duration_ms: number
      /** Speech Pad Ms */
      speech_pad_ms: number
      /** Min Silence At Max Speech */
      min_silence_at_max_speech?: number | null
      /** Use Max Poss Sil At Max Speech */
      use_max_poss_sil_at_max_speech?: boolean | null
    }
    /**
     * VadParametersRequest
     * @description Typed VAD payload for task creation and defaults updates.
     */
    VadParametersRequest: {
      /** Threshold */
      threshold?: number | null
      /** Neg Threshold */
      neg_threshold?: number | null
      /** Min Speech Duration Ms */
      min_speech_duration_ms?: number | null
      /** Max Speech Duration S */
      max_speech_duration_s?: number | 'inf' | null
      /** Min Silence Duration Ms */
      min_silence_duration_ms?: number | null
      /** Speech Pad Ms */
      speech_pad_ms?: number | null
      /** Min Silence At Max Speech */
      min_silence_at_max_speech?: number | null
      /** Use Max Poss Sil At Max Speech */
      use_max_poss_sil_at_max_speech?: boolean | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_config_api_config_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AppConfigResponse']
        }
      }
    }
  }
  get_transcription_engine_defaults_api_config_transcription_engine_defaults_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EngineDefaultsResponse']
        }
      }
    }
  }
  delete_transcription_defaults_api_config_transcription_defaults_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  patch_transcription_defaults_api_config_transcription_defaults_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TranscriptionDefaultsUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TranscriptionDefaultsPatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_export_config_api_config_export_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExportConfigResponse']
        }
      }
    }
  }
  delete_export_defaults_api_config_export_defaults_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  patch_export_defaults_api_config_export_defaults_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExportDefaultsUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExportDefaultsPatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_all_models_api_models_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelListResponse']
        }
      }
    }
  }
  list_active_downloads_api_models_downloads_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActiveModelDownloadsResponse']
        }
      }
    }
  }
  get_model_settings_api_models_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelSettingsResponse']
        }
      }
    }
  }
  patch_model_settings_api_models_settings_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ModelSettingsUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelSettingsResponse']
        }
      }
      /** @description Downloads active for current model directory */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  model_events_api_models_events_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': unknown
        }
      }
    }
  }
  get_model_detail_api_models__model_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelDetailResponse']
        }
      }
      /** @description Unknown model id */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_model_api_models__model_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelDeleteResponse']
        }
      }
      /** @description Unknown model id or not downloaded */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Model is downloading or is configured model */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_download_api_models__model_id__download_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelDownloadStartedResponse']
        }
      }
      /** @description Unknown model id */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Download already in progress */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_download_api_models__model_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelCancelResponse']
        }
      }
      /** @description No active download for this model */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  select_model_api_models__model_id__select_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelSelectResponse']
        }
      }
      /** @description Unknown model id */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Model not downloaded */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_transcriptions_api_transcription_tasks__get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: ('pending' | 'processing' | 'completed' | 'failed' | 'cancelled') | null
        /** @description Max results */
        limit?: number
        /** @description Offset for pagination */
        offset?: number
        /** @description Search keyword for filename */
        q?: string | null
        /** @description Sort field */
        sort_by?: 'created_at' | 'completed_at' | 'status' | 'progress' | 'filename'
        /** @description Sort order */
        order?: 'asc' | 'desc'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_transcription_api_transcription_tasks__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TranscriptionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateTaskResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_transcription_api_transcription_tasks__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_transcription_api_transcription_tasks__task_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CancelTaskResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  batch_cancel_transcriptions_api_transcription_tasks_batch_cancel_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchTaskActionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchTaskActionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  batch_retry_transcriptions_api_transcription_tasks_batch_retry_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchTaskActionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchTaskActionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_task_api_transcription_tasks__task_id__record_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeleteTaskRecordResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  export_transcription_api_transcription_tasks__task_id__export_get: {
    parameters: {
      query?: {
        /** @description Output format; omitted values use persisted export defaults */
        format?: components['schemas']['ExportFormat'] | null
        /** @description Include timestamps (TXT only); omitted values use persisted defaults */
        include_timestamps?: boolean | null
        /** @description Optional output filename for single export. Extension is inferred from selected format. */
        filename?: string | null
        /** @description Save to server instead of download */
        save?: boolean
      }
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description save=false returns subtitle file; save=true returns saved path JSON */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedExportResponse']
          'application/x-subrip': string
          'text/vtt': string
          'text/plain': string
          'text/x-ssa': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  batch_export_api_transcription_tasks_export_batch_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchExportRequest']
      }
    }
    responses: {
      /** @description ZIP archive download */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/zip': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_files_api_files__get: {
    parameters: {
      query?: {
        /** @description Max results */
        limit?: number
        /** @description Offset for pagination */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_file_api_files__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_api_files__post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileUploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  check_integrity_api_files_check_integrity_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrityCheckResponse']
        }
      }
    }
  }
  cleanup_orphans_api_files_cleanup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CleanupResponse']
        }
      }
    }
  }
  get_file_api_files__file_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_file_api_files__file_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
